LEVEL_WIDTH = 60
LEVEL_HEIGHT = 36

STATUS_BAR_WIDTH = 15
STATUS_BAR_HEIGHT = LEVEL_HEIGHT

MESSAGES_BAR_WIDTH = STATUS_BAR_WIDTH + LEVEL_WIDTH
MESSAGES_BAR_HEIGHT = 10

SCREEN_WIDTH = LEVEL_WIDTH + STATUS_BAR_WIDTH
SCREEN_HEIGHT = LEVEL_HEIGHT + MESSAGES_BAR_HEIGHT

ITEMS_ALLOWED_PER_TILE = 1
ENTITIES_ALLOWED_PER_TILE = 1
