FPS = 60

LEVEL_WIDTH = 60
LEVEL_HEIGHT = 36

STATUS_BAR_WIDTH = 15
STATUS_BAR_HEIGHT = LEVEL_HEIGHT

MESSAGES_BAR_WIDTH = STATUS_BAR_WIDTH + LEVEL_WIDTH
MESSAGES_BAR_HEIGHT = 10

MONSTER_STATUS_BAR_WIDTH = 15
MONSTER_STATUS_BAR_HEIGHT = LEVEL_HEIGHT + MESSAGES_BAR_HEIGHT

SCREEN_WIDTH = LEVEL_WIDTH + STATUS_BAR_WIDTH + MONSTER_STATUS_BAR_WIDTH
SCREEN_HEIGHT = LEVEL_HEIGHT + MESSAGES_BAR_HEIGHT

ITEMS_ALLOWED_PER_TILE = 1
ENTITIES_ALLOWED_PER_TILE = 1

DIRECTIONS = {
    "E": (1, 0),
    "N": (0, 1),
    "W": (-1, 0),
    "S": (0, -1),
    "NW": (-1, 1),
    "NE": (1, 1),
    "SW": (-1, -1),
    "SE": (1, -1)
}
