import settings

RIGHT_SIDE_BAR_WIDTH = 28

GUI_BOX_HEIGHT = 16
LEFT_SIDE_BAR_WIDTH = 22
MONSTER_STATUS_BAR_HEIGHT = settings.SCREEN_HEIGHT - GUI_BOX_HEIGHT - 30

MESSAGES_BAR_WIDTH = settings.SCREEN_WIDTH - LEFT_SIDE_BAR_WIDTH


STATUS_BAR_HEIGHT = 16

GAME_STATE_WIDTH = settings.SCREEN_WIDTH
GAME_STATE_HEIGHT = settings.SCREEN_HEIGHT

COMMON_SIGHT_RADIUS = 6
MAX_INFO_LINES = 3
