ROW_LENGTH = 16
WALL_PART = 16 * ROW_LENGTH
FEATURE_PART = WALL_PART + 8 * ROW_LENGTH

TEST_WALLS_ROW = WALL_PART
DUNGEON_WALLS_ROW = WALL_PART + ROW_LENGTH * 1
CAVE_WALLS_ROW = WALL_PART + ROW_LENGTH * 2

DUNGEON_FEATURE_ROW = FEATURE_PART
EQUIPMENT_ITEMS_ROW = FEATURE_PART + ROW_LENGTH * 1
USABLE_ITEMS_ROW = FEATURE_PART + ROW_LENGTH * 2
DUNGEON_ENTITIES_ROW = FEATURE_PART + ROW_LENGTH * 3
TOMB_ENTITIES_ROW = FEATURE_PART + ROW_LENGTH * 4

CENTER_DOT = 15 * ROW_LENGTH + 10
BIG_CENTER_DOT = 15 * ROW_LENGTH + 9

################
#Dungeon Features
################

STAIRS_UP = DUNGEON_FEATURE_ROW
STAIRS_DOWN = DUNGEON_FEATURE_ROW + 1
PILLAR = DUNGEON_FEATURE_ROW + 2
DOOR = DUNGEON_FEATURE_ROW + 3
DOOR_LOCKED = DUNGEON_FEATURE_ROW + 4
DOOR_OPEN = DUNGEON_FEATURE_ROW + 5
FOUNTAIN_FULL = DUNGEON_FEATURE_ROW + 6
FOUNTAIN_EMPTY = DUNGEON_FEATURE_ROW + 7
CORPSE = DUNGEON_FEATURE_ROW + 8
WATER = DUNGEON_FEATURE_ROW + 9

################
#Equipment Items
################

SWORD = EQUIPMENT_ITEMS_ROW
GUN = EQUIPMENT_ITEMS_ROW + 1
HELM = EQUIPMENT_ITEMS_ROW + 2
ARMOR = EQUIPMENT_ITEMS_ROW + 3
BOOTS = EQUIPMENT_ITEMS_ROW + 4
AMULET = EQUIPMENT_ITEMS_ROW + 5
RING = EQUIPMENT_ITEMS_ROW + 6
CLOAK = EQUIPMENT_ITEMS_ROW + 9

################
#Usable Items
################

POTION = USABLE_ITEMS_ROW

##################
#Dungeon Entities
##################

GUNSLINGER = DUNGEON_ENTITIES_ROW
RATMAN = DUNGEON_ENTITIES_ROW + 1
SLIME = DUNGEON_ENTITIES_ROW + 2
GHOST = DUNGEON_ENTITIES_ROW + 3
GOLEM = DUNGEON_ENTITIES_ROW + 4
MAGICIAN = DUNGEON_ENTITIES_ROW + 5
AVATAR = DUNGEON_ENTITIES_ROW + 6
SKELLETON_MAGE = DUNGEON_ENTITIES_ROW + 7
SKELLETON_WARRIOR = DUNGEON_ENTITIES_ROW + 8
SAND_WORM = DUNGEON_ENTITIES_ROW + 9
SAND_WORM_SUBMERGED = DUNGEON_ENTITIES_ROW + 10
GUNSLINGER_THIN = DUNGEON_ENTITIES_ROW + 11

##################
#Tomb Entities
##################

MUMMY = TOMB_ENTITIES_ROW
HORUS = TOMB_ENTITIES_ROW + 1
ANUBIS_SWORD = TOMB_ENTITIES_ROW + 2
ANUBIS_CLUB = TOMB_ENTITIES_ROW + 3
ANUBIS_STAFF = TOMB_ENTITIES_ROW + 4
